[book]
authors = ["Mark Veltzer"]
language = "en"
multilingual = false
src = "src"
title = "rsspell Documentation"

[output.html]
destination = "book/html"
git-repository-url = "https://github.com/veltzer/rsspell"
